name: Docker Installer Download

on:
  workflow_dispatch:
    inputs:

jobs:
  download_installer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download installers
      run: |
         curl -o docker_desktop_installer_windows_amd64.exe "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          docker_desktop_installer_windows_amd64.exe